<?php

namespace App\Exports;

use App\Models\D_livable_sales_csv_output;
use Maatwebsite\Excel\Concerns\FromCollection;
use Maatwebsite\Excel\Concerns\WithHeadings;

class SalesExport implements FromCollection, WithHeadings
{
    /**
    * @return \Illuminate\Support\Collection
    */
    public function collection()
    {
        return D_livable_sales_csv_output::select('id',
                                        'sme_hjn_me_knj',
                                        'sme_hjn_me_kn',
                                        'sebt_flg',
                                        'sngp',
                                        'ybnbng',
                                        'jsh_shzic',
                                        'tel_no1',
                                        'tel_no2',
                                        'mail_adr',
                                        'fax_no',
                                        'kzk_su',
                                        'bkkn_no',
                                        'ankn_kbn',
                                        'kikae_umu',
                                        'nyky_kbo_jiki',
                                        'bkkn_shbt1',
                                        'ysn_frm1',
                                        'ensn1',
                                        'ekikn_frm1',
                                        'ekikn_to1',
                                        'jshcd1',
                                        'tci_frm1',
                                        'ttmn_frm1',
                                        'snyu_frm1',
                                        'mdr_su1',
                                        'bkkn_shbt2',
                                        'ysn_frm2',
                                        'ekikn_frm2',
                                        'ekikn_to2',
                                        'jshcd2',
                                        'ttmn_frm2',
                                        'mdr_su2',
                                        'bkkn_shbt3',
                                        'ysn_frm3',
                                        'jshcd3',
                                        'ttmn_frm3',
                                        'mdr_su3',
                                        'bkyk_niy_biko_rn',
                                        'uktk_ymd',
                                        'egssskcd',
                                        'other1',
                                        'other2',
                                        'other3',
                                        'other4',
                                        'other5',
                                        'other6',
                                        'other7',
                                        'other8',
                                        'other9',
                                        'other10',
                                        'other11',
                                        'other12',
                                        'other13',
                                        'other14',
                                        'other15',
                                        'other16',
                                        'other17',
                                        'other18',
                                        'other19',
                                        'other20',
                                        'other21',
                                        'other22',
                                        'other23',
                                        'other24',
                                        'other25',
                                        'other26',
                                        'other27',
                                        'other28',
                                        'other29',
                                        'other30',
                                        'regist_date',
                                        'output',
                                        'target_name',
                                        'target_name_sub',
                                        'subject')->where('regist_date', '<=', date("Y-m-d H:i:s"))->where('output', '=', '0')->get();
    }

    public function headings(): array {
        return [
            'ID',
            '氏名／法人名＿漢字',
            '氏名／法人名＿カナ',
            '性別フラグ',
            '生年月日',
            '郵便番号',
            '住所／所在地',
            '電話番号1',
            '電話番号2',
            'メールアドレス',
            'ファックス番号',
            '家族数',
            '物件No',
            '案件区分',
            '買換有無',
            '入居希望時期',
            '物件種別1',
            '予算FROM1',
            '沿線1',
            '駅間FROM1',
            '駅間TO1',
            '住所コード1',
            '土地FROM1',
            '建物FROM1',
            '専有FROM1',
            '間取り数1',
            '物件種別2',
            '予算FROM2',
            '駅間FROM2',
            '駅間TO2',
            '住所コード2',
            '建物FROM2',
            '間取り数2',
            '物件種別3',
            '予算FROM3',
            '住所コード3',
            '建物FROM3',
            '間取り数3',
            '売却内容備考欄',
            '受付年月日',
            '営業所組織コード',
            'その他1',
            'その他2',
            'その他3',
            'その他4',
            'その他5',
            'その他6',
            'その他7',
            'その他8',
            'その他9',
            'その他10',
            'その他11',
            'その他12',
            'その他13',
            'その他14',
            'その他15',
            'その他16',
            'その他17',
            'その他18',
            'その他19',
            'その他20',
            'その他21',
            'その他22',
            'その他23',
            'その他24',
            'その他25',
            'その他26',
            'その他27',
            'その他28',
            'その他29',
            'その他30',
            '登録日',
            '出力有無',
            '対象サイト',
            '対象サイト（サブ）',
            '件名'
        ];
    }


}
