<?php

namespace App\Exports;

use App\Models\D_livable_sales_csv_output;
use Maatwebsite\Excel\Concerns\FromCollection;
use Maatwebsite\Excel\Concerns\WithHeadings;

class SalesExport implements FromCollection, WithHeadings
{
    /**
    * @return \Illuminate\Support\Collection
    */
    public function collection()
    {
        return D_livable_sales_csv_output::select('id',
                                        'sme_hjn_me_knj',
                                        'sme_hjn_me_kn',
                                        'sebt_flg',
                                        'sngp',
                                        'ybnbng',
                                        'jsh_shzic',
                                        'tel_no1',
                                        'tel_no2',
                                        'mail_adr',
                                        'fax_no',
                                        'kzk_su',
                                        'bkkn_no',
                                        'ankn_kbn',
                                        'kikae_umu',
                                        'nyky_kbo_jiki',
                                        'bkkn_shbt1',
                                        'ysn_frm1',
                                        'ensn1',
                                        'ekikn_frm1',
                                        'ekikn_to1',
                                        'jshcd1',
                                        'tci_frm1',
                                        'ttmn_frm1',
                                        'snyu_frm1',
                                        'mdr_su1',
                                        'bkkn_shbt2',
                                        'ysn_frm2',
                                        'ekikn_frm2',
                                        'ekikn_to2',
                                        'jshcd2',
                                        'ttmn_frm2',
                                        'mdr_su2',
                                        'bkkn_shbt3',
                                        'ysn_frm3',
                                        'jshcd3',
                                        'ttmn_frm3',
                                        'mdr_su3',
                                        'bkyk_niy_biko_rn',
                                        'uktk_ymd',
                                        'egssskcd',
                                        'other1',
                                        'other2',
                                        'other3',
                                        'other4',
                                        'other5',
                                        'other6',
                                        'other7',
                                        'other8',
                                        'other9',
                                        'other10',
                                        'other11',
                                        'other12',
                                        'other13',
                                        'other14',
                                        'other15',
                                        'other16',
                                        'other17',
                                        'other18',
                                        'other19',
                                        'other20',
                                        'other21',
                                        'other22',
                                        'other23',
                                        'other24',
                                        'other25',
                                        'other26',
                                        'other27',
                                        'other28',
                                        'other29',
                                        'other30',
                                        'regist_date',
                                        'output',
                                        'target_name',
                                        'target_name_sub',
                                        'subject')->where('regist_date', '<=', date("Y-m-d H:i:s"))->where('output', '=', '0')->get();
    }

    public function headings(): array {
        return [
            'ID',
            'SME-HJN-ME-KNJ', 
            'SME-HJN-ME-KN', 
            'SEBT-FLG', 
            'SNGP', 
            'YBNBNG', 
            'JSH-SHZIC', 
            'TEL-NO1', 
            'TEL-NO2', 
            'MAIL-ADR', 
            'FAX-NO', 
            'KZK-SU', 
            'BKKN-NO', 
            'ANKN-KBN', 
            'KIKAE-UMU', 
            'NYKY-KBO-JIKI', 
            'BKKN-SHBT1', 
            'YSN-FRM1', 
            'ENSN1', 
            'EKIKN-FRM1', 
            'EKIKN-TO1', 
            'JSHCD1', 
            'TCI-FRM1', 
            'TTMN-FRM1', 
            'SNYU-FRM1', 
            'MDR-SU1', 
            'BKKN-SHBT2', 
            'YSN-FRM2', 
            'EKIKN-FRM2', 
            'EKIKN-TO2', 
            'JSHCD2', 
            'TTMN-FRM2', 
            'MDR-SU2', 
            'BKKN-SHBT3', 
            'YSN-FRM3', 
            'JSHCD3', 
            'TTMN-FRM3', 
            'MDR-SU3', 
            'BKYK-NIY-BIKO-RN', 
            'UKTK-YMD', 
            'EGSSSKCD', 
            'OTHER1', 
            'OTHER2', 
            'OTHER3', 
            'OTHER4', 
            'OTHER5', 
            'OTHER6', 
            'OTHER7', 
            'OTHER8', 
            'OTHER9', 
            'OTHER10', 
            'OTHER11', 
            'OTHER12', 
            'OTHER13', 
            'OTHER14', 
            'OTHER15', 
            'OTHER16', 
            'OTHER17', 
            'OTHER18', 
            'OTHER19', 
            'OTHER20', 
            'OTHER21', 
            'OTHER22', 
            'OTHER23', 
            'OTHER24', 
            'OTHER25', 
            'OTHER26', 
            'OTHER27', 
            'OTHER28', 
            'OTHER29', 
            'OTHER30', 
            'REGIST-DATE', 
            'OUTPUT', 
            'TARGET-NAME', 
            'TARGET-NAME-SUB', 
            'SUBJECT'
        ];
    }


}
