<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class D_livable_sales_csv_output extends Model
{
    use HasFactory;
    protected $fillable = [
        'id',
        'sme_hjn_me_knj',
        'sme_hjn_me_kn',
        'sebt_flg',
        'sngp',
        'ybnbng',
        'jsh_shzic',
        'tel_no1',
        'tel_no2',
        'mail_adr',
        'fax_no',
        'kzk_su',
        'bkkn_no',
        'ankn_kbn',
        'kikae_umu',
        'nyky_kbo_jiki',
        'bkkn_shbt1',
        'ysn_frm1',
        'ensn1',
        'ekikn_frm1',
        'ekikn_to1',
        'jshcd1',
        'tci_frm1',
        'ttmn_frm1',
        'snyu_frm1',
        'mdr_su1',
        'bkkn_shbt2',
        'ysn_frm2',
        'ekikn_frm2',
        'ekikn_to2',
        'jshcd2',
        'ttmn_frm2',
        'mdr_su2',
        'bkkn_shbt3',
        'ysn_frm3',
        'jshcd3',
        'ttmn_frm3',
        'mdr_su3',
        'bkyk_niy_biko_rn',
        'uktk_ymd',
        'egssskcd',
        'other1',
        'other2',
        'other3',
        'other4',
        'other5',
        'other6',
        'other7',
        'other8',
        'other9',
        'other10',
        'other11',
        'other12',
        'other13',
        'other14',
        'other15',
        'other16',
        'other17',
        'other18',
        'other19',
        'other20',
        'other21',
        'other22',
        'other23',
        'other24',
        'other25',
        'other26',
        'other27',
        'other28',
        'other29',
        'other30',
        'regist_date',
        'output',
        'target_name',
        'target_name_sub',
        'subject'
    ];
}
