<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Sales_csv_output extends Model
{
    use HasFactory;
    
    protected $fillable = [
        'ID',
        'SME-HJN-ME-KNJ', 
        'SME-HJN-ME-KN', 
        'SEBT-FLG', 
        'SNGP', 
        'YBNBNG', 
        'JSH-SHZIC', 
        'TEL-NO1', 
        'TEL-NO2', 
        'MAIL-ADR', 
        'FAX-NO', 
        'KZK-SU', 
        'BKKN-NO', 
        'ANKN-KBN', 
        'KIKAE-UMU', 
        'NYKY-KBO-JIKI', 
        'BKKN-SHBT1', 
        'YSN-FRM1', 
        'ENSN1', 
        'EKIKN-FRM1', 
        'EKIKN-TO1', 
        'JSHCD1', 
        'TCI-FRM1', 
        'TTMN-FRM1', 
        'SNYU-FRM1', 
        'MDR-SU1', 
        'BKKN-SHBT2', 
        'YSN-FRM2', 
        'EKIKN-FRM2', 
        'EKIKN-TO2', 
        'JSHCD2', 
        'TTMN-FRM2', 
        'MDR-SU2', 
        'BKKN-SHBT3', 
        'YSN-FRM3', 
        'JSHCD3', 
        'TTMN-FRM3', 
        'MDR-SU3', 
        'BKYK-NIY-BIKO-RN', 
        'UKTK-YMD', 
        'EGSSSKCD', 
        'OTHER1', 
        'OTHER2', 
        'OTHER3', 
        'OTHER4', 
        'OTHER5', 
        'OTHER6', 
        'OTHER7', 
        'OTHER8', 
        'OTHER9', 
        'OTHER10', 
        'OTHER11', 
        'OTHER12', 
        'OTHER13', 
        'OTHER14', 
        'OTHER15', 
        'OTHER16', 
        'OTHER17', 
        'OTHER18', 
        'OTHER19', 
        'OTHER20', 
        'OTHER21', 
        'OTHER22', 
        'OTHER23', 
        'OTHER24', 
        'OTHER25', 
        'OTHER26', 
        'OTHER27', 
        'OTHER28', 
        'OTHER29', 
        'OTHER30', 
        'REGIST-DATE', 
        'OUTPUT', 
        'TARGET-NAME', 
        'TARGET-NAME-SUB', 
        'SUBJECT'
    ];
}
